name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: add course
        run: echo "\ntestcourse, test" >> courses.txt
      - name: add & commit
        run: |
          git add .
          git commit -m "Stuff"
          git push